server:
  port: 8080

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  application:
    name: storageManager
  datasource:     #?????
#    password: 123456gbs   #??????
    password: 123456gbs
    username: root     #??????
    driver-class-name: com.mysql.cj.jdbc.Driver  #?????????
    url: jdbc:mysql://localhost:3306/cangku?serverTimezone=GMT%2B8&characterEncoding=utf8


mybatis-plus:
  #??mapper xml?????
  mapper-locations: classpath:com/example/storagemanager/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl